// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4TirqkAiU8lfDfOPveF5R4_PpJJi4e5w',
    appId: '1:777766429062:web:03ca2a059a5319c7308c07',
    messagingSenderId: '777766429062',
    projectId: 'ittisal-c6e70',
    authDomain: 'ittisal-c6e70.firebaseapp.com',
    storageBucket: 'ittisal-c6e70.firebasestorage.app',
    measurementId: 'G-6YEPM8Q21V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs4NIgAe2CJqKUu6BygfyOzOfCtFzfeZQ',
    appId: '1:777766429062:android:945effdec82d10a7308c07',
    messagingSenderId: '777766429062',
    projectId: 'ittisal-c6e70',
    storageBucket: 'ittisal-c6e70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnBV82eVneXPujN57e_Nt7oEvitODsZAo',
    appId: '1:777766429062:ios:c01139457f57fbd4308c07',
    messagingSenderId: '777766429062',
    projectId: 'ittisal-c6e70',
    storageBucket: 'ittisal-c6e70.firebasestorage.app',
    iosBundleId: 'com.example.ittisalFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnBV82eVneXPujN57e_Nt7oEvitODsZAo',
    appId: '1:777766429062:ios:c01139457f57fbd4308c07',
    messagingSenderId: '777766429062',
    projectId: 'ittisal-c6e70',
    storageBucket: 'ittisal-c6e70.firebasestorage.app',
    iosBundleId: 'com.example.ittisalFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4TirqkAiU8lfDfOPveF5R4_PpJJi4e5w',
    appId: '1:777766429062:web:3b692a7c28544e37308c07',
    messagingSenderId: '777766429062',
    projectId: 'ittisal-c6e70',
    authDomain: 'ittisal-c6e70.firebaseapp.com',
    storageBucket: 'ittisal-c6e70.firebasestorage.app',
    measurementId: 'G-PDZECN1QBY',
  );
}
